### ISSUE TITLE
develop code upload form

### ISSUE THREAD

**Issue by tatarchm** [locoschool/locoschool#13]
A simple web app to upload projects at the end of each session. Very basic interface: participant name, file selection. Not clear where it will store stuff in the backend.

**Comment by voshch** [comment]
https://codecommit.locoschool.vshch.com/
https://codecommit.locoschool.vshch.com/admin locoschool:stream5

feel free to experiment, this is configured to a demo branch on https://github.com/voshch/locoschool-data/tree/stream-dev

**Comment by voshch** [comment]
user management designed as 'user picks and self-adds their own name, but will see it as a suggestion next time'. list of suggestions can be edited by admins.
user pairing is realized with symlinks on a per-lesson basis. use https://codecommit.locoschool.vshch.com/files/ to explore and download.

**Comment by voshch** [comment]
standard workflow for us is changing the lesson name ('context') before each lesson. rest is automatic.

**Comment by voshch** [comment]
open to qol suggestions
