### ISSUE TITLE
pick get-to-know game

### ISSUE THREAD

**Issue by tatarchm** [locoschool/locoschool#18]
We need some icebreaker game to get to know each other. If you have suggestions please write them in the comments, we'll pick one on Sunday.

**Comment by NColdGit** [comment]
1. Розбитися на пари, розповісти один одному про себе (улюблена комп'ютерна гра, мова програмування(мрія), може щось цікаве про програмування)
2. Ім'я та якусь ідею про будинок: що можна б булу зробити, якщо є необмежені ресурси та все можливо: 15 секунд
3. Гра на другий день: що б ти обрав з ... (два варіанти все одно що)

**Comment by tatarchm** [comment]
1. There's a circle of chairs, one chair fewer than the number of people. Everyone sits, one person stands in the middle. This person names a criterion for switching (dark hair, speaks English, ...). Everyone who meets the criterion has to find a new place. The person without a place goes to the middle and continues.
2. Terminator (collaborative game). There's a circle (or some other shape) of chairs, one free. The Terminator has to take the free chair - in this case the game ends. The Terminator slowly starts walking towards the free chair, while participants can switch places according to some rule. For example, those who are right next to the free chair cannot sit in it, others can. Only one person at a time can switch places. The group has to work out a collaborative strategy to keep the Terminator from reaching the free chair.

**Comment by NColdGit** [comment]
What do we choose? After an active game, we will need time to calm them down. I am not sure, that we have this time

**Comment by tatarchm** [comment]
We can also go for something simple like this.

Get everyone to stand in a line or sit in a circle. The first person says their name and a favorite thing.
The second person then says their name and a favorite thing, as well as the name and thing of the person before them.
Each person after that adds the names and items of all of the people before them.

Not too active but adds some interaction.

**Comment by NColdGit** [comment]
I corrected my comment with games

**Comment by NColdGit** [comment]
I can't remember anything when I am nervous. It can also be with somebody. :) I think the game should be short and very easy on the first day

**Comment by NColdGit** [comment]
> We can also go for something simple like this.
> 
> Get everyone to stand in a line or sit in a circle. The first person says their name and a favorite thing. The second person then says their name and a favorite thing, as well as the name and thing of the person before them. Each person after that adds the names and items of all of the people before them.
> 
> Not too active but adds some interaction.

In this game, we can have a situation when someone doesn't remember or says something incorrectly, and children can laugh. And this game has "winners": everyone who remembers and can repeat everything.
