### ISSUE TITLE
prepare safety instructions

### ISSUE THREAD

**Issue by tatarchm** [locoschool/locoschool#21]
Let's collect a (short) list of things we want to mention as safety instructions. I'll put them on a slide on Sunday.

**Comment by tatarchm** [comment]
I put my current version [here](https://docs.google.com/presentation/d/1L_pcKCzTk4wJ4NBNB_XFCX5AkM8TIoVIa8zA8ALQ2pk/edit?usp=sharing)

**Comment by voshch** [comment]
i'd say a quick thing about contact voltage, essentially 'this thing can't really hurt you (unless you take a bite out of it)'.
i'll add 2 more slides, if that sounds good?
